name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version:
          - "3.4.2"
          - "3.3.7"
          - "3.2.7"
        rabbitmq-image-tag:
          - "rabbitmq:4-management"

    env:
      CI: true
      RUNS: 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Start RabbitMQ and ToxiProxy with Docker Compose
        run: export RABBITMQ_IMAGE=${{ matrix.rabbitmq-image-tag }} && docker compose up -d --wait

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rspec -c -fd spec/higher_level_api spec/lower_level_api spec/issues

      - name: Stop and cleanup services
        if: always()
        run: docker compose down

